"""rename enum types and rename scheduled_tasks

Revision ID: 16fb6ab40074
Revises: ce06be54f680
Create Date: 2025-04-19 13:08:08.315871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16fb6ab40074'
down_revision: Union[str, None] = 'ce06be54f680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('scheduled_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('SCHEDULED', 'TRIGGERED', 'CANCELLED', name='scheduled_status', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('scheduled_id')
    )
    op.drop_table('scheduled_task')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='run_status',
        new_values=['CREATED', 'SCHEDULED', 'TRIGGERED'],
        affected_columns=[TableReference(table_schema='public', table_name='runs', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='scheduled_status',
        new_values=['SCHEDULED', 'TRIGGERED', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='scheduled_tasks', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='scheduled_status',
        new_values=['scheduled', 'triggered', 'cancelled'],
        affected_columns=[TableReference(table_schema='public', table_name='scheduled_tasks', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='run_status',
        new_values=['created', 'scheduled', 'triggered'],
        affected_columns=[TableReference(table_schema='public', table_name='runs', column_name='status')],
        enum_values_to_rename=[],
    )
    op.create_table('scheduled_task',
    sa.Column('scheduled_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'triggered', 'cancelled', name='scheduled_status', create_type=False), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], name='scheduled_task_job_id_fkey'),
    sa.PrimaryKeyConstraint('scheduled_id', name='scheduled_task_pkey')
    )
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
