"""Initial migration

Revision ID: 518b33b308bb
Revises: 
Create Date: 2025-04-18 19:51:35.253118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518b33b308bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('system_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('system_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('scheduler', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_dependencies',
    sa.Column('dependence_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('completed_job_id', sa.Integer(), nullable=False),
    sa.Column('trigger_job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completed_job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['trigger_job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('dependence_id'),
    sa.UniqueConstraint('completed_job_id', 'trigger_job_id', name='uq_completed_job_triggered_job_pair_idx')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('external_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('created', 'scheduled', 'triggered', name='run_status'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('scheduled_tasks',
    sa.Column('scheduled_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'triggered', 'cancelled', name='scheduled_status'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('scheduled_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_tasks')
    op.drop_table('runs')
    op.drop_table('job_dependencies')
    op.drop_table('jobs')
    op.drop_table('systems')
    # ### end Alembic commands ###
