"""Add unique index completed_job_id+trigger_job_id to job_dependencies

Revision ID: 51abd08e774c
Revises: 8ef3f82c89db
Create Date: 2025-04-16 13:37:42.461556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51abd08e774c'
down_revision: Union[str, None] = '8ef3f82c89db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_completed_job_triggered_job_pair_idx', 'job_dependencies', ['completed_job_id', 'trigger_job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_completed_job_triggered_job_pair_idx', 'job_dependencies', type_='unique')
    # ### end Alembic commands ###
