"""Initial migration

Revision ID: 9daac7c98cff
Revises: 
Create Date: 2025-04-14 15:35:51.991745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9daac7c98cff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('system_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('system_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('scheduler', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_dependencies',
    sa.Column('dependence_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('completed_job_id', sa.Integer(), nullable=False),
    sa.Column('trigger_job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completed_job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['trigger_job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('dependence_id')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('external_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('job_dependencies')
    op.drop_table('jobs')
    op.drop_table('systems')
    # ### end Alembic commands ###
