"""Add unique index to job_dependencies

Revision ID: af4ecf32404e
Revises: 11db7b2eca20
Create Date: 2025-04-15 23:07:40.305117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4ecf32404e'
down_revision: Union[str, None] = '11db7b2eca20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_index_job_dependence', 'job_dependencies', ['completed_job_id', 'trigger_job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_index_job_dependence', 'job_dependencies', type_='unique')
    # ### end Alembic commands ###
